### ISSUE TITLE
Github Actions doesn't set SHELL variable

### ISSUE THREAD

**Issue by ManasJayanth** [ManasJayanth/esy-package#10]
Because of this, we have to set it manually in the `workflow.yml`. Do this automatically in `esy-package`

```
      - name: Run end-to-end tests on the package 
        run: DEBUG=bale*,verdaccio* esy-package
        shell: bash
        env:
          SHELL: "bash.exe" # HACK!! For some weird reason, $SHELL in Github actions' Windows' bash shell doesn't set this environment variable. We rely on it to figure if path normalisation is necessary on Gitbash Windows
```
